import {
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  TextRun,
  type ISectionOptions,
} from 'docx'

/**
 * Turns the Word editor's TipTap document into a real .docx.
 *
 * WHY A GENERATOR AND NOT docx-editor.dev's AUTOMATION API. That library's
 * core is Apache-2.0 and fits this app, but it is BROWSER-ONLY and its
 * Office.js-compatible automation API (`@docx-editor.dev/editor-api`) is under
 * the EigenPal Pro Licence at $500/month. Gabe's call was the free editor for
 * editing plus the `docx` package for output, which is what this is: a pure
 * function over the editor's own JSON, no licence and no browser required.
 *
 * WHY .docx AT ALL when the app already exports PDF: ATS parsers still handle
 * Word more reliably than PDF, and a large share of application forms accept
 * .doc/.docx only. A CV that cannot be uploaded is not a CV.
 *
 * IT IS DELIBERATELY PLAIN. No colours, no tables, no text boxes, no columns,
 * no headers or footers -- every one of those is a known ATS parsing hazard,
 * and this file exists to produce something a parser can read rather than
 * something that looks designed. `atsLint` already enforces the same rule on
 * the content side.
 */

/** The subset of TipTap's JSON this reads. Anything else is ignored, not thrown on. */
export interface TipTapNode {
  type?: string
  text?: string
  marks?: { type?: string }[]
  content?: TipTapNode[]
  attrs?: Record<string, unknown>
}

function runsFrom(node: TipTapNode): TextRun[] {
  if (typeof node.text === 'string') {
    const marks = new Set((node.marks ?? []).map((m) => m.type))
    return [
      new TextRun({
        text: node.text,
        bold: marks.has('bold'),
        italics: marks.has('italic'),
      }),
    ]
  }
  return (node.content ?? []).flatMap(runsFrom)
}

/** Flatten a node's text, for the cases where runs are not needed. */
function textOf(node: TipTapNode): string {
  if (typeof node.text === 'string') return node.text
  return (node.content ?? []).map(textOf).join('')
}

const HEADING_FOR: Record<number, (typeof HeadingLevel)[keyof typeof HeadingLevel]> = {
  1: HeadingLevel.HEADING_1,
  2: HeadingLevel.HEADING_2,
  3: HeadingLevel.HEADING_3,
}

function paragraphsFrom(node: TipTapNode): Paragraph[] {
  switch (node.type) {
    case 'heading': {
      const level = Number(node.attrs?.level ?? 1)
      return [
        new Paragraph({
          heading: HEADING_FOR[level] ?? HeadingLevel.HEADING_3,
          children: runsFrom(node),
        }),
      ]
    }
    case 'paragraph': {
      // An empty paragraph is spacing the author put there on purpose.
      const runs = runsFrom(node)
      return [new Paragraph({ children: runs.length > 0 ? runs : [new TextRun('')] })]
    }
    case 'bulletList':
    case 'orderedList':
      return (node.content ?? []).flatMap((item) =>
        // REAL LIST NUMBERING, not a literal "- " prefix. A hyphen typed into
        // the text is what an ATS sees as part of the sentence; a Word list is
        // structure it can strip.
        (item.content ?? []).map(
          (block) =>
            new Paragraph({
              children: runsFrom(block),
              ...(node.type === 'bulletList'
                ? { bullet: { level: 0 } }
                : { numbering: { reference: 'cv-numbering', level: 0 } }),
            })
        )
      )
    case 'hardBreak':
      return [new Paragraph({ children: [new TextRun('')] })]
    default: {
      if (node.content) return node.content.flatMap(paragraphsFrom)
      const text = textOf(node)
      return text ? [new Paragraph({ children: [new TextRun(text)] })] : []
    }
  }
}

/** The document body, exposed so it can be asserted without packing a zip. */
export function sectionsFrom(doc: unknown): ISectionOptions[] {
  const root = (doc ?? {}) as TipTapNode
  const children = (root.content ?? []).flatMap(paragraphsFrom)
  return [
    {
      properties: {
        page: {
          // 0.8in on every side, matching the editor's own letter preview --
          // so what was on screen is what comes out.
          margin: { top: 1152, right: 1152, bottom: 1152, left: 1152 },
        },
      },
      children: children.length > 0 ? children : [new Paragraph({ children: [new TextRun('')] })],
    },
  ]
}

export async function buildDocx(doc: unknown, title: string): Promise<Buffer> {
  const document = new Document({
    // Written into the file's properties so a recruiter's file manager and
    // Word's own title bar show the CV's name rather than "Document1".
    title: title.trim() || 'CV',
    description: 'Generated by Worktrack',
    numbering: {
      config: [
        {
          reference: 'cv-numbering',
          levels: [{ level: 0, format: 'decimal', text: '%1.', alignment: 'left' }],
        },
      ],
    },
    sections: sectionsFrom(doc),
  })
  return Packer.toBuffer(document)
}
