#!/usr/bin/env node
/**
 * Generates the icon components from the Figma export.
 *
 *   node scripts/generate-icons.mjs
 *
 * Generated rather than hand-written. 26 icons is enough that a transcription
 * error is certain, and a regenerable set can be re-pulled when Figma changes
 * instead of being patched by hand and drifting.
 *
 * Geometry notes, both learned the hard way in this project:
 *
 *   Ellipses use strokeAlign INSIDE in Figma, so the drawn circle sits wholly
 *   within its box and the visual radius is (w - strokeWidth) / 2, not w / 2.
 *
 *   Figma rotation is counter-clockwise about the node's own origin; SVG's
 *   rotate() is clockwise. The Moon carries a 19.8 degree rotation applied to
 *   straighten it, so its sign has to be flipped and its centre given
 *   explicitly, or it lands mirrored.
 */
import { readFileSync, writeFileSync } from 'node:fs'

const src = JSON.parse(readFileSync(new URL('./icon-source.json', import.meta.url)))
const { viewBox: VB, strokeWidth: SW, icons } = src

function shapeToSvg(s) {
  if (s.t === 'c') {
    const r = (s.w - SW) / 2
    const cx = s.x + s.w / 2
    const cy = s.y + s.w / 2
    return `<circle cx="${cx}" cy="${cy}" r="${r}" />`
  }
  const rot = s.rot ? ` rotate(${-s.rot} ${s.x} ${s.y})` : ''
  return `<path d="${s.d}" transform="translate(${s.x} ${s.y})${rot}" />`
}

const header = `// GENERATED by scripts/generate-icons.mjs from scripts/icon-source.json.
// Do not edit by hand -- re-export from Figma and regenerate instead.
//
// Every icon takes currentColor so the semantic tokens drive its colour, and is
// aria-hidden because each one sits beside a text label. An icon that is the
// only content of a control needs an accessible name on the control, not here.
import type { SVGProps } from 'react'

export interface IconProps extends Omit<SVGProps<SVGSVGElement>, 'width' | 'height'> {
  /** Rendered size in px. Defaults to 20, the size the set was drawn at. */
  size?: number
}

function svgProps(size: number) {
  return {
    width: size,
    height: size,
    viewBox: '0 0 ${VB} ${VB}',
    fill: 'none',
    stroke: 'currentColor',
    strokeWidth: ${SW},
    strokeLinecap: 'round' as const,
    strokeLinejoin: 'round' as const,
    'aria-hidden': true,
  }
}
`

const components = icons.map(({ n, s }) => {
  const body = s.map(shapeToSvg).join('\n      ')
  return `
export function ${n}Icon({ size = 20, ...props }: IconProps) {
  return (
    <svg {...svgProps(size)} {...props}>
      ${body}
    </svg>
  )
}`
}).join('\n')

const registry = `

/** Every icon by name. Used by the gallery and to assert the set is complete. */
export const icons = {
${icons.map(({ n }) => `  ${n}: ${n}Icon,`).join('\n')}
} as const

export type IconName = keyof typeof icons
`

writeFileSync(new URL('../src/components/icons/index.tsx', import.meta.url), header + components + registry)
console.log(`Generated ${icons.length} icon components.`)
