// GENERATED by scripts/generate-icons.mjs from scripts/icon-source.json.
// Do not edit by hand -- re-export from Figma and regenerate instead.
//
// Every icon takes currentColor so the semantic tokens drive its colour, and is
// aria-hidden because each one sits beside a text label. An icon that is the
// only content of a control needs an accessible name on the control, not here.
import type { SVGProps } from 'react'

export interface IconProps extends Omit<SVGProps<SVGSVGElement>, 'width' | 'height'> {
  /** Rendered size in px. Defaults to 20, the size the set was drawn at. */
  size?: number
}

function svgProps(size: number) {
  return {
    width: size,
    height: size,
    viewBox: '0 0 20 20',
    fill: 'none',
    stroke: 'currentColor',
    strokeWidth: 1.75,
    strokeLinecap: 'round' as const,
    strokeLinejoin: 'round' as const,
    'aria-hidden': true,
  }
}

export function OverviewIcon({ size = 20, ...props }: IconProps) {
  return (
    <svg {...svgProps(size)} {...props}>
      <path d="M 0 0 L 15 0 L 15 6 L 0 6 L 0 0 Z M 0 9 L 7 9 L 7 15 L 0 15 L 0 9 Z M 9 9 L 15 9 L 15 15 L 9 15 L 9 9 Z" transform="translate(2.5 2.5)" />
    </svg>
  )
}

export function ApplicationsIcon({ size = 20, ...props }: IconProps) {
  return (
    <svg {...svgProps(size)} {...props}>
      <path d="M 0 0 L 0 13 M 6 0 L 6 13 M 12 0 L 12 13" transform="translate(4 3.5)" />
    </svg>
  )
}

export function CalendarIcon({ size = 20, ...props }: IconProps) {
  return (
    <svg {...svgProps(size)} {...props}>
      <path d="M 0 5.5 L 13 5.5 M 3.5 0 L 3.5 4 M 9.5 0 L 9.5 4 M 0 2 L 13 2 L 13 13 L 0 13 L 0 2 Z" transform="translate(3.5 3.5)" />
    </svg>
  )
}

export function DocumentsIcon({ size = 20, ...props }: IconProps) {
  return (
    <svg {...svgProps(size)} {...props}>
      <path d="M 6 0 L 0 0 L 0 15 L 10 15 L 10 4 M 6 0 L 10 4 M 6 0 L 6 4 L 10 4" transform="translate(5 2.5)" />
    </svg>
  )
}

export function AnalyticsIcon({ size = 20, ...props }: IconProps) {
  return (
    <svg {...svgProps(size)} {...props}>
      <path d="M 0 0 L 0 14 L 14 14 M 2.5 10.5 L 6 6 L 9 8.5 L 13 3" transform="translate(3 3)" />
    </svg>
  )
}

export function SettingsIcon({ size = 20, ...props }: IconProps) {
  return (
    <svg {...svgProps(size)} {...props}>
      <path d="M 0 0 L 6 0 M 10 0 L 14 0 M 0 7 L 4 7 M 8 7 L 14 7" transform="translate(3 6.5)" />
    </svg>
  )
}

export function PlusIcon({ size = 20, ...props }: IconProps) {
  return (
    <svg {...svgProps(size)} {...props}>
      <path d="M 6 0 L 6 12 M 0 6 L 12 6" transform="translate(4 4)" />
    </svg>
  )
}

export function SearchIcon({ size = 20, ...props }: IconProps) {
  return (
    <svg {...svgProps(size)} {...props}>
      <circle cx="9" cy="9" r="4.625" />
      <path d="M 0 0 L 4.5 4.5" transform="translate(12.5 12.5)" />
    </svg>
  )
}

export function MenuIcon({ size = 20, ...props }: IconProps) {
  return (
    <svg {...svgProps(size)} {...props}>
      <path d="M 0 0 L 14 0 M 0 4 L 14 4 M 0 8 L 14 8" transform="translate(3 6)" />
    </svg>
  )
}

export function ArrowRightIcon({ size = 20, ...props }: IconProps) {
  return (
    <svg {...svgProps(size)} {...props}>
      <path d="M 0 5 L 12 5 M 12 5 L 7 0 M 12 5 L 7 10" transform="translate(4 5)" />
    </svg>
  )
}

export function UploadIcon({ size = 20, ...props }: IconProps) {
  return (
    <svg {...svgProps(size)} {...props}>
      <path d="M 7 10 L 7 0 M 7 0 L 3 4 M 7 0 L 11 4 M 0 10 L 0 14 L 14 14 L 14 10" transform="translate(3 3)" />
    </svg>
  )
}

export function DownloadIcon({ size = 20, ...props }: IconProps) {
  return (
    <svg {...svgProps(size)} {...props}>
      <path d="M 7 0 L 7 10 M 7 10 L 3 6 M 7 10 L 11 6 M 0 10 L 0 14 L 14 14 L 14 10" transform="translate(3 3)" />
    </svg>
  )
}

export function CloseIcon({ size = 20, ...props }: IconProps) {
  return (
    <svg {...svgProps(size)} {...props}>
      <path d="M 0 0 L 10 10 M 10 0 L 0 10" transform="translate(5 5)" />
    </svg>
  )
}

export function CheckIcon({ size = 20, ...props }: IconProps) {
  return (
    <svg {...svgProps(size)} {...props}>
      <path d="M 0 5 L 4 9 L 12 0" transform="translate(4 5.5)" />
    </svg>
  )
}

export function ClockIcon({ size = 20, ...props }: IconProps) {
  return (
    <svg {...svgProps(size)} {...props}>
      <circle cx="10" cy="10" r="6.125" />
      <path d="M 0 0 L 0 4 L 3 6" transform="translate(10 6)" />
    </svg>
  )
}

export function ExternalIcon({ size = 20, ...props }: IconProps) {
  return (
    <svg {...svgProps(size)} {...props}>
      <path d="M 7.5 0 L 13 0 M 13 0 L 13 5.5 M 13 0 L 5.5 7.5 M 10.5 8.5 L 10.5 13 L 0 13 L 0 2.5 L 4.5 2.5" transform="translate(3.5 3.5)" />
    </svg>
  )
}

export function LockIcon({ size = 20, ...props }: IconProps) {
  return (
    <svg {...svgProps(size)} {...props}>
      <path d="M 2 5.5 L 2 3 C 2 1 3.4 0 5 0 C 6.6 0 8 1 8 3 L 8 5.5 M 0 5.5 L 10 5.5 L 10 13 L 0 13 L 0 5.5 Z" transform="translate(5 3.5)" />
    </svg>
  )
}

export function DatabaseIcon({ size = 20, ...props }: IconProps) {
  return (
    <svg {...svgProps(size)} {...props}>
      <path d="M 0 0 L 13 0 L 13 4 L 0 4 L 0 0 Z M 0 8 L 13 8 L 13 12 L 0 12 L 0 8 Z" transform="translate(3.5 4)" />
    </svg>
  )
}

export function MailIcon({ size = 20, ...props }: IconProps) {
  return (
    <svg {...svgProps(size)} {...props}>
      <path d="M 0 0 L 14 0 M 0 0 L 0 9 L 14 9 L 14 0 M 0 0 L 7 5 L 14 0" transform="translate(3 5.5)" />
    </svg>
  )
}

export function ShieldIcon({ size = 20, ...props }: IconProps) {
  return (
    <svg {...svgProps(size)} {...props}>
      <path d="M 6 0 L 12 2.5 L 12 7 C 12 11 9.2 13.4 6 14.5 C 2.8 13.4 0 11 0 7 L 0 2.5 L 6 0 Z" transform="translate(4 3)" />
    </svg>
  )
}

export function SwatchIcon({ size = 20, ...props }: IconProps) {
  return (
    <svg {...svgProps(size)} {...props}>
      <path d="M 0 0 L 5.5 0 L 5.5 13 L 0 13 L 0 0 Z M 7.5 0 L 13 0 L 13 13 L 7.5 13 L 7.5 0 Z" transform="translate(3.5 3.5)" />
    </svg>
  )
}

export function TextIcon({ size = 20, ...props }: IconProps) {
  return (
    <svg {...svgProps(size)} {...props}>
      <path d="M 0 0 L 12 0 M 0 5 L 12 5 M 0 10 L 7 10" transform="translate(4 5)" />
    </svg>
  )
}

export function LayersIcon({ size = 20, ...props }: IconProps) {
  return (
    <svg {...svgProps(size)} {...props}>
      <path d="M 0 9 L 7 13 L 14 9 M 7 0 L 14 4 L 7 8 L 0 4 L 7 0 Z" transform="translate(3 3)" />
    </svg>
  )
}

export function PlayIcon({ size = 20, ...props }: IconProps) {
  return (
    <svg {...svgProps(size)} {...props}>
      <path d="M 0 0 L 9.5 6 L 0 12 L 0 0 Z" transform="translate(6.5 4)" />
    </svg>
  )
}

export function SunIcon({ size = 20, ...props }: IconProps) {
  return (
    <svg {...svgProps(size)} {...props}>
      <circle cx="10" cy="10" r="2.625" />
      <path d="M 7.5 0 L 7.5 1.7 M 7.5 13.3 L 7.5 15 M 0 7.5 L 1.7 7.5 M 13.3 7.5 L 15 7.5 M 2.2 2.2 L 3.4 3.4 M 11.6 11.6 L 12.8 12.8 M 12.8 2.2 L 11.6 3.4 M 3.4 11.6 L 2.2 12.8" transform="translate(2.5 2.5)" />
    </svg>
  )
}

export function MoonIcon({ size = 20, ...props }: IconProps) {
  return (
    <svg {...svgProps(size)} {...props}>
      <path d="M 10 1.4 C 6.7 2.5 4.3 5.6 4.3 9.2 C 4.3 10.8 4.8 12.3 5.6 13.6 C 2.4 13 0 10.2 0 6.9 C 0 3.1 3.1 0 6.9 0 C 8 0 9.1 0.5 10 1.4 Z" transform="translate(2.99 5.3) rotate(-19.8 2.99 5.3)" />
    </svg>
  )
}

/** Every icon by name. Used by the gallery and to assert the set is complete. */
export const icons = {
  Overview: OverviewIcon,
  Applications: ApplicationsIcon,
  Calendar: CalendarIcon,
  Documents: DocumentsIcon,
  Analytics: AnalyticsIcon,
  Settings: SettingsIcon,
  Plus: PlusIcon,
  Search: SearchIcon,
  Menu: MenuIcon,
  ArrowRight: ArrowRightIcon,
  Upload: UploadIcon,
  Download: DownloadIcon,
  Close: CloseIcon,
  Check: CheckIcon,
  Clock: ClockIcon,
  External: ExternalIcon,
  Lock: LockIcon,
  Database: DatabaseIcon,
  Mail: MailIcon,
  Shield: ShieldIcon,
  Swatch: SwatchIcon,
  Text: TextIcon,
  Layers: LayersIcon,
  Play: PlayIcon,
  Sun: SunIcon,
  Moon: MoonIcon,
} as const

export type IconName = keyof typeof icons
